# Example configuration file for piccolo

# List of Art-Net LED devices
devices:
  - name: "strip1"
    ip: "192.168.1.50"
    pixel_count: 150
    universe: 0
  - name: "strip2"
    ip: "192.168.1.51"
    pixel_count: 150
    universe: 1

# Groups can be created via the REST API. Example payload:
# name: "stage"
# segments:
#   - device: "strip1"
#     start: 0
#     length: 75
#   - device: "strip2"
#     start: 0
#     length: 75
